### ISSUE TITLE
from 3d models to distance maps

### ISSUE THREAD

**Issue by tarak77** [tjs23/nuc_dynamics#10]
Hi @tjs23 , is there a way to go from a single cell (haploid/diploid) 3d models at high resolutions(say 10 or 20kb) to genomewide distance matrix?

**Comment by tjs23** [comment]
HI Tarak, I don't presently have any of my own tools to do this, but it should be straightforward to implement e.g. using scipy.distance.pdist(coords) and matplotlib.pyplot.matshow.

**Comment by tarak77** [comment]
Hi @tjs23, Yes that's true and i have got distance maps chromosome wise for 20kb bins. Was just wondering if there's a better way to do it genome-wide more efficiently for higher resolutions. Thanks again!

**Comment by tjs23** [comment]
If you're happy with an upper limit then k-d trees, e.g. scipy.spatial.KDTree.sparse_distance_matrix may be handy.

**Comment by tarak77** [comment]
ok will check that
