### ISSUE TITLE
Can you explain how the 3D coordinates were updated according to the force definitions?

### ISSUE THREAD

**Issue by renxwise** [tjs23/nuc_dynamics#5]
Hi tjs23, Nuc_dynamics is excellent. I have read the supplementary information of the Nature paper and capture the main idea of the algorithm. But I did not find the update formula for the 3D coordinates given the force definitions and the temperature. Can you give me a brief explanation? Thanks.

**Comment by tjs23** [comment]
The coordinate update is from the application of the basic Newtonian laws of motion. See the updateMotion() and updateVelocity() functions in dyn_util.pyx. Essentially the change in position is velocity*time + 0.5*acceleration*time^2. Note that the calculation of the acceleration is force/mass with an extra term that tries to adjust the observed temperature (from the average kinetic energy) toward the target temperature.
