### ISSUE TITLE
License for nuc_dynamics

### ISSUE THREAD

**Issue by gesinecauer** [tjs23/nuc_dynamics#7]
Hello! I'm not seeing any license information for nuc_dynamics. If I somehow missed it, would you mind pointing me in the right direction? And if not, would it be possible to add a license?

Thanks!

**Comment by tjs23** [comment]
I have now added LGPLv3.

**Comment by gesinecauer** [comment]
Great, thanks for your help!

**Comment by gesinecauer** [comment]
Hello, sorry to bother you again about this. I was wondering if you wouldn't mind switching over to a BSD or MIT license. I was hoping to make use of some of your code, and it looks like I actually wouldn't be able to with the LGPLv3 license.

Thank you!

**Comment by gesinecauer** [comment]
Hey @tjs23, I just wanted to check in again about this. Would you mind using a BSD or MIT license? Thanks!

**Comment by tjs23** [comment]
I really want to have the LGPL license here. I don't want derivations of my code becoming closed-source. What's the problem with LGPL? You can copy, modify and adapt the code and even use it in commercial products...
