### ISSUE TITLE
Viewing output file of nuc_dynamics

### ISSUE THREAD

**Issue by pqyNUS** [tjs23/nuc_dynamics#8]
Hi,

I am quite new to bioinformatics, and would like to know how can I view the output "Cell_1_contacts.pdb" file after following the default parameters specified in the readme? 
In addition, i would like to look at the structure in a specified region e.g chr8:1-500,000. How should i go about doing this?

**Comment by tjs23** [comment]
I recommend viewing the PDB format structures in a molecular structure viewer, e.g. PyMOL, UCSF Chimera etc. Details of the format's use for chromosomes is at the top of the PDB file in the REMARK section. For example chr8:1-500,000 would correspond to the first rows in chain 'h' with residue number '1' (indicating the first 1 Mb) with atoms [NC]1 to [NC]5, assuming 100 Kb particle sizes.
